# base image
FROM node:22-alpine

# set working directory
WORKDIR /backend

# install pnpm
RUN npm install -g pnpm

# copy dependencies and install
COPY api-app/package.json api-app/pnpm-lock.yaml ./api-app/
WORKDIR /backend/api-app
RUN pnpm install

# copy source
COPY api-app ./

# build the app
RUN pnpm run build

# expose app port
EXPOSE 3000

CMD sh -c "pnpm run migration:run && pnpm run start:prod"