# base image
FROM node:22-alpine

# set working directory
WORKDIR /frontend

# install pnpm
RUN npm install -g pnpm

# copy dependencies and install
COPY web-app/package.json web-app/pnpm-lock.yaml ./web-app/
WORKDIR /frontend/web-app
RUN pnpm install

# copy source
COPY web-app ./

# build the app
RUN pnpm run build

# expose app port
EXPOSE 4173

CMD ["pnpm", "preview", "--host"]
