version: '3.9'

services:
  app:
    build: .
    container_name: se-school-5-ruslan-melnyk
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      Weather_API_KEY: ${Weather_API_KEY}
    command: >
      sh -c "
      pnpm install &&
      pnpm run build &&
      pnpm run migration:run &&
      pnpm run start:prod
      "
